### ISSUE TITLE
[RR] Approval Link in Email is missing slash

### ISSUE THREAD

**Issue by sbehrendsohc** [CentralAZ/Rock-CentralAZ#58]
### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a room reservation is submitted, the email to confirm has a broken link on the "View Reservation" button.
We are seeing this for the link:
https://www.orchardcore.inforeservationdetail/?ReservationId=5

And it appears to be missing the "/" after our name 
orchardcore.info**/**?ReservationId=5

### Steps to Reproduce

1. Has user fill out room reservation
2. Have personal with approval check their email
3. Click the link

**Expected behavior:** 

Take you to the room reservation to approve or reject it.

**Actual behavior:** 

Broken page URL.

### Versions

* **Rock Version:** Rock Version: Rock McKinley 6.9
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@sbehrendsohc the Room Management > "Room Reservation Approval Notification" workflow uses the Internal Application Root url (Global Attribute) setting -- and it should have a slash at the end of the url as seen in this example:
![image](https://user-images.githubusercontent.com/383807/32908866-1bc0d410-cac2-11e7-973f-a0395bc114f6.png)

It sounds like your environment is missing that slash.  So you can either correct your Global Attribute setting or you can adjust the workflow's email body values and add the slash there (however other things in your environment would probably still be broken since the trailing slash is expected in that Global Attribute).
