### ISSUE TITLE
[RR] Enhancement - Insufficient Details in Room Reservation Search Report

### ISSUE THREAD

**Issue by edcylam** [CentralAZ/Rock-CentralAZ#76]
### Description

We need to generate Excel reports generated in Search Reservation in order for our custodians to know how to set up the rooms. However, there are a few important details missing in the report:

- The Resources column only indicates the types of resources needed for the room but doesn't include their quantities

<img width="969" alt="screen shot 2018-06-25 at 5 21 07 pm" src="https://user-images.githubusercontent.com/24534451/41882222-9a62e988-789c-11e8-97ea-41c86b4e5a5d.png">

- The report needs to include the ministry, notes section, and answers to the room & resource reservation questions. Although the notes are included in the print feature (thanks @nairdo  for pointing it out), we want the report available in Excel format so that it makes it easier for us to filter things out, delete unnecessary columns, or add new info 

- When more than one room is included in a reservation, the actual reservation page and report need to be able to specify which resource is for which room

IMPORTANT: Our church building is used as a school facility during weekdays. As a result, we have a lot of room configuration changes between weekdays and weekends. We have just recently migrated to Rock and would need to create all the room reservation requests before the new school year begins in late August. These feature requests are very crucial for us to generate complete room setup reports needed by our custodians, or we would require a lot of extra copy and paste work to create these reports. 

### Versions

* **Rock Version:** 7.4  
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@edcylam We are not able to add additional reporting features at this time.  I recommend you create a custom data view (with Applies To: "Reservation") and then use that in a custom Report and pick the fields you you want show in the excel export.  NOTE: Since you currently can't easily get a reservation's locations or resources through the report fields drop-down list, you'll need to use Lava's (entity commands) to get those more complicated items.
