### ISSUE TITLE
[RR] Enhancement - Separate Resources for Each Room in Single a Multi-Room Reservation

### ISSUE THREAD

**Issue by edcylam** [CentralAZ/Rock-CentralAZ#77]
### Description

When making a reservation with multiple rooms, we would like to be able to designate which resources are for which rooms in the Resources section.

### Versions

* **Rock Version:** 7.4  
* **Client Culture Setting:** en-US

**Comment by tcavaletto** [comment]
You can do this one of two ways. For resources tied to specific rooms, you can attach them to those rooms so that they get automatically added to your reservation:
![image](https://user-images.githubusercontent.com/5482014/77809629-b8984100-704d-11ea-953c-f9ecfdab83a7.png)

Alternatively, you can include a question on those resources asking which rooms you want to place them in:

![image](https://user-images.githubusercontent.com/5482014/77809607-a0282680-704d-11ea-8ae9-4e4d9d3a20a1.png)
